#pragma once
// ImGui
#include <imgui.h>
#include <./ImGuizmo/ImGuizmo.h>
#include <Extensions/IconFontsCppHeaders/IconsFontAwesome5.h>
// Cereal
#include <cereal/cereal.hpp>
#include <cereal/archives/binary.hpp>
#include <cereal/archives/json.hpp>
#include <cereal/types/array.hpp>
#include <cereal/types/bitset.hpp>
#include <cereal/types/memory.hpp>
#include <cereal/types/polymorphic.hpp>
#include <cereal/types/unordered_map.hpp>
#include <cereal/types/utility.hpp>
#include <cereal/types/vector.hpp>
#include <cereal/types/set.hpp>
#include <cereal/types/string.hpp>
//Components
#include "ecs.h"
// Graphics State
#include "blend.h"
#include "depth_stencil.h"
#include "rasterizer.h"
#include "sampler.h"
// Helper
#include "easing.h"
#include "string_helper.h"
//// System
//#include "constant_buffer.h"
//#include "depth_map.h"
//#include "dx11_configurator.h"
//#include "enum_state_map.h"
//#include "frame_buffer.h"
//#include "framework.h"
//#include "fullscreen_quad.h"
//#include "gbuffer.h"
//#include "graphics_state.h"
//#include "high_resolution_timer.h"
//#include "input_system.h"
//#include "state_machine.h"
//#include "vertex_shader.h"
//#include "window.h"
